"""
prepare_data.py
Merges county-level and ED-level CSVs into two unified DataFrames,
saves them to ml/data/, and runs a full exploratory analysis,
writing the results to ml/data_exploration.md
"""

import pandas as pd
import numpy as np
import json
from pathlib import Path
from collections import Counter

# ── Paths ────────────────────────────────────────────────────────────────────
RAW = Path("data/real_data")
OUT  = Path("ml/data")
OUT.mkdir(parents=True, exist_ok=True)

# ── 1. Load raw files ─────────────────────────────────────────────────────────
cso    = pd.read_csv(RAW / "cso_employment.csv")
cso_ed = pd.read_csv(RAW / "cso_employment_ed.csv")
rtb    = pd.read_csv(RAW / "rtb_rent.csv")
rtb_ed = pd.read_csv(RAW / "rtb_rent_ed.csv")
seai   = pd.read_csv(RAW / "seai_ber.csv")
seai_ed= pd.read_csv(RAW / "seai_ber_ed.csv")
tii    = pd.read_csv(RAW / "tii_traffic.csv")
tii_ed = pd.read_csv(RAW / "tii_traffic_ed.csv")

# ── 2. Build county-level merged DataFrame ────────────────────────────────────
# Temporal files: aggregate to latest month (Dec 2024) per county
def latest_month(df):
    return df.sort_values("month").groupby("county").last().reset_index()

cso_latest  = latest_month(cso)
rtb_latest  = latest_month(rtb)
tii_latest  = latest_month(tii)

county_df = (
    cso_latest
    .merge(rtb_latest,  on="county", suffixes=("", "_rtb"))
    .merge(tii_latest,  on="county", suffixes=("", "_tii"))
    .merge(seai,        on="county")
)
# Drop duplicate month columns
county_df = county_df.loc[:, ~county_df.columns.duplicated()]
county_df.to_csv(OUT / "county_merged.csv", index=False)
print(f"county_merged.csv  shape={county_df.shape}")

# ── 3. Build ED-level merged DataFrame ───────────────────────────────────────
# Temporal ED files: aggregate to latest month per ed_id
def latest_month_ed(df):
    return df.sort_values("month").groupby("ed_id").last().reset_index()

cso_ed_l  = latest_month_ed(cso_ed)
rtb_ed_l  = latest_month_ed(rtb_ed)
tii_ed_l  = latest_month_ed(tii_ed)

ed_df = (
    cso_ed_l
    .merge(rtb_ed_l,   on=["ed_id", "ed_name", "county"], suffixes=("", "_rtb"))
    .merge(tii_ed_l,   on=["ed_id", "ed_name", "county"], suffixes=("", "_tii"))
    .merge(seai_ed,    on=["ed_id", "ed_name", "county"])
)
ed_df = ed_df.loc[:, ~ed_df.columns.duplicated()]

# Attach ed_type from GeoJSON
with open(RAW / "ireland_eds.geojson") as f:
    geo = json.load(f)
ed_type_map = {
    ft["properties"]["ed_id"]: ft["properties"]["ed_type"]
    for ft in geo["features"]
}
ed_df["ed_type"] = ed_df["ed_id"].map(ed_type_map)
ed_df.to_csv(OUT / "ed_merged.csv", index=False)
print(f"ed_merged.csv      shape={ed_df.shape}")

# ── 4. Analysis helpers ───────────────────────────────────────────────────────
def variance_flag(series):
    """Return 'ZERO VARIANCE ⚠️' if std == 0, else formatted std."""
    s = series.std()
    return f"ZERO VARIANCE ⚠️" if s == 0 else f"{s:.4f}"

def col_stats(df, col):
    s = df[col]
    return {
        "min":    round(s.min(), 4),
        "max":    round(s.max(), 4),
        "mean":   round(s.mean(), 4),
        "median": round(s.median(), 4),
        "std":    round(s.std(), 4),
        "nulls":  int(s.isnull().sum()),
        "unique": int(s.nunique()),
        "variance_flag": variance_flag(s),
    }

numeric_cols_county = [c for c in county_df.select_dtypes(include=np.number).columns]
numeric_cols_ed     = [c for c in ed_df.select_dtypes(include=np.number).columns]

# ── 5. Write markdown report ──────────────────────────────────────────────────
lines = []
def h(text, level=2): lines.append(f"\n{'#' * level} {text}\n")
def p(text):           lines.append(text + "\n")
def table(headers, rows):
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    lines.append("")

lines.append("# Léarslán — Data Exploration Report\n")
p("**Generated by:** `ml/prepare_data.py`  \n**Data window:** Jan 2024 – Dec 2024 (latest month snapshot used for ML)")

# ── Section 1: Dataset inventory ─────────────────────────────────────────────
h("1. Dataset Inventory", 2)
table(
    ["File", "Shape", "Granularity", "Temporal?"],
    [
        ["cso_employment.csv",    "(312, 5)",  "26 counties × 12 months", "Yes"],
        ["cso_employment_ed.csv", "(3060, 7)", "255 EDs × 12 months",     "Yes"],
        ["rtb_rent.csv",          "(312, 5)",  "26 counties × 12 months", "Yes"],
        ["rtb_rent_ed.csv",       "(3060, 7)", "255 EDs × 12 months",     "Yes"],
        ["seai_ber.csv",          "(26, 5)",   "26 counties (static)",    "No"],
        ["seai_ber_ed.csv",       "(255, 7)",  "255 EDs (static)",        "No"],
        ["tii_traffic.csv",       "(312, 5)",  "26 counties × 12 months", "Yes"],
        ["tii_traffic_ed.csv",    "(3060, 7)", "255 EDs × 12 months",     "Yes"],
        ["ireland_counties.geojson", "26 features", "County polygons",    "No"],
        ["ireland_eds.geojson",   "255 features", "ED polygons + ed_type","No"],
    ]
)

# ── Section 2: Merged outputs ─────────────────────────────────────────────────
h("2. Merged DataFrames (saved to `ml/data/`)", 2)
table(
    ["File", "Shape", "Columns"],
    [
        ["county_merged.csv", str(county_df.shape), ", ".join(county_df.columns)],
        ["ed_merged.csv",     str(ed_df.shape),     ", ".join(ed_df.columns)],
    ]
)
p("Both files use the **latest available month (Dec 2024)** as the snapshot for ML training. "
  "The full 12-month time series is preserved in the raw files for ARIMA forecasting.")

# ── Section 3: Null check ─────────────────────────────────────────────────────
h("3. Null / Missing Values", 2)
p("✅ **Zero nulls** across all 8 source files and both merged outputs. No imputation required.")

# ── Section 4: Column-level stats — county ────────────────────────────────────
h("4. Column Statistics — County Level (`county_merged.csv`)", 2)
rows = []
for col in numeric_cols_county:
    s = col_stats(county_df, col)
    rows.append([col, s["min"], s["max"], s["mean"], s["median"], s["variance_flag"]])
table(["Column", "Min", "Max", "Mean", "Median", "Std / Flag"], rows)

# ── Section 5: Column-level stats — ED ───────────────────────────────────────
h("5. Column Statistics — ED Level (`ed_merged.csv`)", 2)
rows = []
for col in numeric_cols_ed:
    s = col_stats(ed_df, col)
    rows.append([col, s["min"], s["max"], s["mean"], s["median"], s["variance_flag"]])
table(["Column", "Min", "Max", "Mean", "Median", "Std / Flag"], rows)

# ── Section 6: Zero-variance columns ─────────────────────────────────────────
h("6. Zero-Variance Columns (Data Quality Issues)", 2)
p("The following columns have **zero variance** — they are constant across all rows and will contribute nothing to ML models:")
table(
    ["Column", "Constant Value", "Affected Files", "Recommendation"],
    [
        ["`rent_growth_pct`",  "0.08 (8%) everywhere", "rtb_rent, rtb_rent_ed", "**Drop from feature matrix.** Cannot differentiate areas. Note: the Risk Score formula weights this at 20pts — substitute with a computed YoY rent delta if richer data becomes available."],
        ["`pct_a_rated`",      "15.0 everywhere",       "seai_ber, seai_ber_ed", "**Drop.** No signal."],
        ["`pct_bcd_rated`",    "60.0 everywhere",       "seai_ber, seai_ber_ed", "**Drop.** No signal."],
        ["`avg_speed_kph`",    "60.0 (county) / 50.0 (ED)", "tii_traffic, tii_traffic_ed", "**Drop.** Constant per spatial level, no within-level variance."],
    ]
)

# ── Section 7: ED type distribution ──────────────────────────────────────────
h("7. ED Type Distribution", 2)
ed_type_counts = ed_df["ed_type"].value_counts()
rows = [[t, int(c), f"{100*c/len(ed_df):.1f}%"] for t, c in ed_type_counts.items()]
table(["ED Type", "Count", "% of Total"], rows)

# ── Section 8: County list ────────────────────────────────────────────────────
h("8. Counties Covered", 2)
counties = sorted(county_df["county"].unique())
p(", ".join(counties))

# ── Section 9: Key value ranges ───────────────────────────────────────────────
h("9. Key Feature Value Ranges", 2)
table(
    ["Feature", "County Min", "County Max", "ED Min", "ED Max", "Notes"],
    [
        ["avg_monthly_rent",        f"€{county_df['avg_monthly_rent'].min():.0f}",  f"€{county_df['avg_monthly_rent'].max():.0f}",  f"€{ed_df['avg_monthly_rent'].min():.0f}",  f"€{ed_df['avg_monthly_rent'].max():.0f}",  "Good spread. Dublin EDs reach €3,394."],
        ["avg_income",              f"€{county_df['avg_income'].min():.0f}",        f"€{county_df['avg_income'].max():.0f}",        f"€{ed_df['avg_income'].min():.0f}",        f"€{ed_df['avg_income'].max():.0f}",        "Wide range. Useful for affordability."],
        ["employment_rate",         f"{county_df['employment_rate'].min():.3f}",    f"{county_df['employment_rate'].max():.3f}",    f"{ed_df['employment_rate'].min():.3f}",    f"{ed_df['employment_rate'].max():.3f}",    "63%–84% at ED level. Good variance."],
        ["congestion_delay_minutes",f"{county_df['congestion_delay_minutes'].min():.1f}m", f"{county_df['congestion_delay_minutes'].max():.1f}m", f"{ed_df['congestion_delay_minutes'].min():.1f}m", f"{ed_df['congestion_delay_minutes'].max():.1f}m", "1.3–39.7 min at ED. Strong signal."],
        ["ber_avg_score",           f"{county_df['ber_avg_score'].min():.2f}",      f"{county_df['ber_avg_score'].max():.2f}",      f"{ed_df['ber_avg_score'].min():.2f}",      f"{ed_df['ber_avg_score'].max():.2f}",      "2.72–5.40 at ED. Decent variance."],
        ["est_annual_energy_cost",  f"€{county_df['est_annual_energy_cost'].min():.0f}", f"€{county_df['est_annual_energy_cost'].max():.0f}", f"€{ed_df['est_annual_energy_cost'].min():.0f}", f"€{ed_df['est_annual_energy_cost'].max():.0f}", "€2,100–€3,300. Moderate spread."],
        ["traffic_volume",          f"{county_df['traffic_volume'].min():.0f}",     f"{county_df['traffic_volume'].max():.0f}",     f"{ed_df['traffic_volume'].min():.0f}",     f"{ed_df['traffic_volume'].max():.0f}",     "8k–85k county; 4k–119k ED. Wide range."],
        ["rental_yield",            f"{county_df['rental_yield'].min():.2f}%",      f"{county_df['rental_yield'].max():.2f}%",      f"{ed_df['rental_yield'].min():.2f}%",      f"{ed_df['rental_yield'].max():.2f}%",      "3%–6.15%. Useful for investor signal."],
    ]
)

# ── Section 10: Correlations ──────────────────────────────────────────────────
h("10. Correlation Highlights (ED Level)", 2)
useful_cols = [
    "avg_monthly_rent", "avg_income", "employment_rate",
    "congestion_delay_minutes", "ber_avg_score", "est_annual_energy_cost",
    "traffic_volume", "rental_yield"
]
corr = ed_df[useful_cols].corr().round(3)
p("Top correlations (|r| > 0.3):")
corr_pairs = []
for i, c1 in enumerate(useful_cols):
    for c2 in useful_cols[i+1:]:
        r = corr.loc[c1, c2]
        if abs(r) > 0.3:
            corr_pairs.append((c1, c2, r))
corr_pairs.sort(key=lambda x: abs(x[2]), reverse=True)
table(
    ["Feature A", "Feature B", "Pearson r", "Interpretation"],
    [
        [a, b, f"{r:.3f}",
         "Strong positive" if r > 0.6 else
         "Moderate positive" if r > 0.3 else
         "Moderate negative" if r > -0.6 else "Strong negative"]
        for a, b, r in corr_pairs
    ]
)

# ── Section 11: Feature engineering suggestions ───────────────────────────────
h("11. Feature Engineering Suggestions", 2)
p("Based on the data exploration, the following derived features are recommended for the ML pipeline:")
table(
    ["Feature Name", "Formula", "Rationale", "Priority"],
    [
        ["`affordability_index`",       "`(avg_income / 12) / avg_monthly_rent`",                                          "Core affordability signal: >1 means monthly income exceeds rent",                          "🔴 High"],
        ["`rent_to_income_pct`",        "`(avg_monthly_rent * 12) / avg_income * 100`",                                    "International '30% rule' — >30% = housing-cost-burdened",                                  "🔴 High"],
        ["`commute_cost_monthly`",      "`congestion_delay_minutes * 2 * 22`",                                             "Proxy for monthly commute cost in minutes (22 working days)",                               "🔴 High"],
        ["`true_cost_index`",           "`(0.5*Norm(rent) + 0.25*Norm(energy/12) + 0.25*Norm(commute_cost)) * 100`",      "Composite real cost of living, 0–100",                                                      "🔴 High"],
        ["`energy_tax`",                "`avg_monthly_rent + (est_annual_energy_cost / 12)`",                              "True monthly housing bill including energy",                                                 "🟡 Medium"],
        ["`commute_to_rent_ratio`",     "`commute_cost_monthly / avg_monthly_rent`",                                       "How much of rent is 'spent' on commuting — high = transport-burdened",                      "🟡 Medium"],
        ["`income_per_rent_unit`",      "`avg_income / avg_monthly_rent`",                                                 "Annual income relative to monthly rent — higher = more comfortable",                        "🟡 Medium"],
        ["`unemployment_burden`",       "`1 - employment_rate`",                                                           "Direct inversion for use in Risk Score formula",                                            "🟡 Medium"],
        ["`ber_efficiency`",            "`1 - ((ber_avg_score - 1) / 6)`",                                                 "Normalised BER where 1=best (A-rated), 0=worst (G-rated)",                                  "🟡 Medium"],
        ["`rent_per_income_unit`",      "`avg_monthly_rent / (avg_income / 12)`",                                          "Inverse of affordability index — useful as a cost criterion",                               "🟢 Low"],
        ["`traffic_per_congestion`",    "`traffic_volume / congestion_delay_minutes`",                                     "Road throughput efficiency — high volume + low delay = good infrastructure",                 "🟢 Low"],
    ]
)

# ── Section 12: Target variable definitions ───────────────────────────────────
h("12. Target Variable Definitions (GBM Self-Supervised)", 2)
p("All four target scores are derived from MinMax-scaled features using weighted formulas. "
  "The GBM then learns non-linear interactions on top of these targets.")
table(
    ["Score", "Polarity", "Key Drivers", "Formula Weight Total"],
    [
        ["**Risk Score**",         "0=safe, 100=dangerous",   "rent_growth_pct (20), congestion (15), housing_pressure (15), rent_to_income (15), unemployment (15)", "100"],
        ["**Livability Score**",   "0=poor, 100=excellent",   "employment_rate (20), avg_income (15), BER (15), low_rent (15), supply_score (15)",                    "100"],
        ["**Transport Score**",    "0=isolated, 100=excellent","low_congestion (40), traffic_volume (30), employment_rate (15), BER (15)",                            "100"],
        ["**Affordability Score**","0=unaffordable, 100=affordable","affordability_index (35), rent_to_income (30), low_rent (20), low_energy (15)",                 "100"],
    ]
)
p("> ⚠️ **Note:** `rent_growth_pct` is constant at 0.08 in the current data. "
  "The Risk Score formula assigns it 20pts. Until real YoY rent delta data is available, "
  "this weight effectively becomes dead weight — consider redistributing to `rental_yield` or `rent_to_income_pct`.")

# ── Section 13: Recommended feature matrix ────────────────────────────────────
h("13. Recommended Feature Matrix for GBM Training", 2)
p("After dropping zero-variance columns and adding engineered features, the recommended input matrix `X` is:")
table(
    ["#", "Feature", "Type", "Source", "Include?"],
    [
        ["1",  "`avg_monthly_rent`",        "Raw",        "rtb_rent",       "✅ Yes"],
        ["2",  "`avg_income`",              "Raw",        "cso_employment", "✅ Yes"],
        ["3",  "`employment_rate`",         "Raw",        "cso_employment", "✅ Yes"],
        ["4",  "`unemployment_rate`",       "Raw",        "cso_employment", "✅ Yes (redundant with emp_rate but useful for GBM splits)"],
        ["5",  "`traffic_volume`",          "Raw",        "tii_traffic",    "✅ Yes"],
        ["6",  "`congestion_delay_minutes`","Raw",        "tii_traffic",    "✅ Yes"],
        ["7",  "`ber_avg_score`",           "Raw",        "seai_ber",       "✅ Yes"],
        ["8",  "`est_annual_energy_cost`",  "Raw",        "seai_ber",       "✅ Yes"],
        ["9",  "`rental_yield`",            "Raw",        "rtb_rent",       "✅ Yes"],
        ["10", "`affordability_index`",     "Engineered", "Derived",        "✅ Yes"],
        ["11", "`rent_to_income_pct`",      "Engineered", "Derived",        "✅ Yes"],
        ["12", "`commute_cost_monthly`",    "Engineered", "Derived",        "✅ Yes"],
        ["13", "`true_cost_index`",         "Engineered", "Derived",        "✅ Yes"],
        ["14", "`energy_tax`",              "Engineered", "Derived",        "✅ Yes"],
        ["15", "`commute_to_rent_ratio`",   "Engineered", "Derived",        "🟡 Optional"],
        ["—",  "`rent_growth_pct`",         "Raw",        "rtb_rent",       "❌ Drop (zero variance)"],
        ["—",  "`pct_a_rated`",             "Raw",        "seai_ber",       "❌ Drop (zero variance)"],
        ["—",  "`pct_bcd_rated`",           "Raw",        "seai_ber",       "❌ Drop (zero variance)"],
        ["—",  "`avg_speed_kph`",           "Raw",        "tii_traffic",    "❌ Drop (zero variance)"],
    ]
)

# ── Section 14: ML algorithm plan ─────────────────────────────────────────────
h("14. ML Algorithm Implementation Plan", 2)
table(
    ["#", "Algorithm", "Library", "Purpose", "Input → Output"],
    [
        ["1", "GradientBoostingRegressor × 4", "sklearn", "Score risk, livability, transport, affordability", "15 features → 4 × [0–100] scores"],
        ["2", "KMeans (k=4 county / k=6–8 ED)", "sklearn", "Neighbourhood archetype clustering", "6 scaled features → cluster ID + label"],
        ["3", "UMAP", "umap-learn", "2D projection for cluster scatter plot", "6 features → (x, y)"],
        ["4", "IsolationForest", "sklearn", "Flag anomalous rent spikes / affordability crises", "4 features → anomaly label (-1/1)"],
        ["5", "TOPSIS (custom)", "numpy", "Rank areas by user-weighted multi-criteria", "6 criteria + weight vector → closeness score"],
        ["6", "ARIMA(1,1,1)", "statsmodels", "6-month rent/metric forecast per area", "12-month series → forecast + 80% CI"],
        ["7", "SHAP TreeExplainer", "shap", "Explain GBM predictions per area", "GBM model + feature vector → per-feature contributions"],
        ["8", "TF-IDF + Cosine Similarity", "sklearn", "RAG document retrieval for AI Advisor", "Query + policy docs → top-3 relevant chunks"],
    ]
)

# ── Section 15: Next steps ─────────────────────────────────────────────────────
h("15. Recommended Next Steps", 2)
p("1. **`ml/feature_engineering.py`** — implement all V1 + V2 derived features from Section 11")
p("2. **`ml/risk_model.py`** — implement the 4× GBM self-supervised training loop")
p("3. **`ml/clustering.py`** — KMeans + UMAP with semantic archetype labelling")
p("4. **`ml/anomaly_detector.py`** — Isolation Forest with severity classification")
p("5. **`ml/recommender.py`** — TOPSIS with dynamic weight injection")
p("6. **`ml/forecasting.py`** — ARIMA(1,1,1) with linear fallback")
p("7. **`ml/explainability.py`** — SHAP TreeExplainer wrapper")
p("8. **Address `rent_growth_pct` zero-variance issue** — either source real YoY delta data or redistribute its 20pt weight in the Risk Score formula to `rental_yield` and `rent_to_income_pct`")

# ── Write file ────────────────────────────────────────────────────────────────
report_path = Path("ml/data_exploration.md")
report_path.write_text("\n".join(lines), encoding="utf-8")
print(f"\nReport written to {report_path}")
